cypress:
  image: cypress/included:12.17.4
  baseUrl: "https://example.cypress.io"
  browser: "chrome"
  env: {}

  git:
    url: "https://github.com/fernale/cyproject.git"
    branch: "main"
    path: "cyproject"  # Subdirectory within the repo

resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"

job:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600

persistence:
  storageClass: "standard"
  size: "10Gi"
