# values.yaml
cypress:
  image: cypress/included:12.17.4
  baseUrl: "https://example.cypress.io"  # Update with your target URL
  browser: "chrome"
  env: {}
  
  git:
    url: "https://github.com/fernale/cyproject.git"
    branch: "main"
    path: "cyproject"  # Matches your directory structure

resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"

job:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600  # Cleanup after 1 hour

persistence:
  storageClass: "standard"
  size: "10Gi"
