apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-artifacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-artifacts
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-artifacts
    spec:
      initContainers:
        - name: fix-permissions
          image: alpine:3.14
          command:
            - sh
            - -c
            - |
              # Fix permissions for Nginx (UID 101)
              chown -R 101:101 /usr/share/nginx/html || true
              chmod -R 755 /usr/share/nginx/html || true
          volumeMounts:
            - name: cypress-artifacts
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cypress-artifacts
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: cypress-artifacts
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-cypress-pvc
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
