apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cypress-gui
  template:
    metadata:
      labels:
        app: cypress-gui
    spec:
      initContainers:
        - name: clone-tests
          image: alpine/git:2.40.1
          command:
            - sh
            - -c
            - |
              set -ex
              git clone --depth 1 -b {{ .Values.cypress.git.branch }} {{ .Values.cypress.git.url }} /repo
              cp -r /repo/{{ .Values.cypress.git.path }}/* /tests/
          volumeMounts:
            - name: test-suite
              mountPath: /tests
      containers:
        - name: cypress-gui
          image: {{ .Values.cypress.image }}
          workingDir: /tests
          command: ["npx", "cypress", "open", "--project", ".", "--host", "0.0.0.0", "--port", "{{ .Values.gui.port }}"]
          ports:
            - containerPort: {{ .Values.gui.port }}
          env:
            - name: CYPRESS_baseUrl
              value: "{{ .Values.cypress.baseUrl }}"
          volumeMounts:
            - name: test-suite
              mountPath: /tests
      volumes:
        - name: test-suite
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-cypress-pvc
