apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gui.port }}
      targetPort: {{ .Values.gui.port }}
  selector:
    app: cypress-gui
